name: 'Cpp gRPC Setup'
description: 'Setup gRPC C++ environment'
inputs:
  grpc-version:
    description: Version of grpc to setup
    required: false
    default: 1.60.0
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: box
  color: blue
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'