name: 'Cpp gRPC Setup'
description: 'Setup gRPC C++ environment'
inputs:
  grpc-version:
    description: Version of grpc to setup
    required: false
    default: 1.60.0
  grpc-installation-path:
    description: Installation path of grpc
    required: false
    default: grpc
  include-google-test:
    description: Should include google test
    required: false
    default: true
  google-test-version:
    description: Google-test tag version
    required: false
    default: 1.14.0
  token:
    description: Used to pull grpc distributions from hindicator/grpc-versions. Since there's a default, this is typically not supplied by the user.
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: box
  color: blue
